# Copyright (c) 2017 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.

################################################################################

includes:
- ../app_locations.yml

################################################################################

# ---- 3dsMaxPlus

settings.tk-multi-snapshot.3dsmaxplus.asset_step: &settings_tk-multi-snapshot_3dsmaxplus_asset_step
  template_snapshot: max_asset_snapshot_model
  template_work: max_asset_work_model
  location: "@apps.tk-multi-snapshot.location"

settings.tk-multi-snapshot.3dsmaxplus.material_step: &settings_tk-multi-snapshot_3dsmaxplus_material_step
  template_snapshot: max_customentity03_snapshot
  template_work: max_customentity03_work
  location: "@apps.tk-multi-snapshot.location"

settings.tk-multi-snapshot.3dsmaxplus.scene_step: &settings_tk-multi-snapshot_3dsmaxplus_scene_step
  template_snapshot: max_customentity02_snapshot
  template_work: max_customentity02_work
  location: "@apps.tk-multi-snapshot.location"

settings.tk-multi-snapshot.3dsmaxplus.shot_step: &settings_tk-multi-snapshot_3dsmaxplus_shot_step
  template_snapshot: max_shot_snapshot
  template_work: max_shot_work
  location: "@apps.tk-multi-snapshot.location"

settings.tk-multi-snapshot.3dsmaxplus.shot_step_post: &settings_tk-multi-snapshot_3dsmaxplus_shot_step_post
  template_snapshot: max_shot_snapshot
  template_work: max_shot_work
  location: "@apps.tk-multi-snapshot.location"

settings.tk-multi-snapshot.3dsmaxplus.shot_step_render: &settings_tk-multi-snapshot_3dsmaxplus_shot_step_render
  template_snapshot: max_shot_snapshot
  template_work: max_shot_work
  location: "@apps.tk-multi-snapshot.location"

settings.tk-multi-snapshot.3dsmaxplus.showroom_step_ar: &settings_tk-multi-snapshot_3dsmaxplus_showroom_step_ar
  template_snapshot: max_shot_snapshot
  template_work: max_shot_work
  location: "@apps.tk-multi-snapshot.location"

settings.tk-multi-snapshot.3dsmaxplus.showroom_step_post: &settings_tk-multi-snapshot_3dsmaxplus_showroom_step_post
  template_snapshot: max_shot_snapshot
  template_work: max_shot_work
  location: "@apps.tk-multi-snapshot.location"

settings.tk-multi-snapshot.3dsmaxplus.showroom_step_render: &settings_tk-multi-snapshot_3dsmaxplus_showroom_step_render
  template_snapshot: max_shot_snapshot
  template_work: max_shot_work
  location: "@apps.tk-multi-snapshot.location"
settings.tk-multi-snapshot.3dsmaxplus.showroom_step_sprite: &settings_tk-multi-snapshot_3dsmaxplus_showroom_step_sprite
  template_snapshot: max_shot_snapshot
  template_work: max_shot_work
  location: "@apps.tk-multi-snapshot.location"    



################################################################################

# ---- 3dsMax

#settings.tk-multi-snapshot.3dsmax.asset_step:
 # <<: *settings_tk-multi-snapshot_3dsmaxplus_asset_step
 # hook_scene_operation: "{engine}/tk-multi-snapshot/basic/scene_operation.py"
#settings.tk-multi-snapshot.3dsmax.shot_step:
 # <<: *settings_tk-multi-snapshot_3dsmaxplus_shot_step
# hook_scene_operation: "{engine}/tk-multi-snapshot/basic/scene_operation.py"

# shot_step_post
settings.tk-multi-snapshot.3dsmax.shot_step_post:
  template_snapshot: max_asset_snapshot_model
  template_work: max_asset_work_model
  location: "@apps.tk-multi-snapshot.location"

# shot_step_render
settings.tk-multi-snapshot.3dsmax.shot_step_render:
  template_snapshot: max_asset_snapshot_model
  template_work: max_asset_work_model
  location: "@apps.tk-multi-snapshot.location"

# showroom_step_ar
settings.tk-multi-snapshot.3dsmax.showroom_step_ar:
  template_snapshot: max_asset_snapshot_model
  template_work: max_asset_work_model
  location: "@apps.tk-multi-snapshot.location"

# showroom_step_post
settings.tk-multi-snapshot.3dsmax.showroom_step_post:
  template_snapshot: max_asset_snapshot_model
  template_work: max_asset_work_model
  location: "@apps.tk-multi-snapshot.location"

# showroom_step_render
settings.tk-multi-snapshot.3dsmax.showroom_step_render:
  template_snapshot: max_asset_snapshot_model
  template_work: max_asset_work_model
  location: "@apps.tk-multi-snapshot.location"

# showroom_step_sprite
settings.tk-multi-snapshot.3dsmax.showroom_step_sprite:
  template_snapshot: max_asset_snapshot_model
  template_work: max_asset_work_model
  location: "@apps.tk-multi-snapshot.location"

# asset step - Model
settings.tk-multi-snapshot.3dsmax.asset_step:
  template_snapshot: max_asset_snapshot_model
  template_work: max_asset_work_model
  location: "@apps.tk-multi-snapshot.location"

# customentity01 - Material Step
settings.tk-multi-snapshot.3dsmax.material_step:
  template_snapshot: max_customentity03_snapshot
  template_work: max_customentity03_work
  location: "@apps.tk-multi-snapshot.location"  

 # customentity01 - Scene Step
settings.tk-multi-snapshot.3dsmax.scene_step:
  template_snapshot: max_customentity02_snapshot
  template_work: max_customentity02_snapshot
  location: "@apps.tk-multi-snapshot.location"  

# shot step
settings.tk-multi-snapshot.3dsmax.shot_step:
  template_snapshot: max_shot_snapshot
  template_work: max_shot_work
  location: "@apps.tk-multi-snapshot.location"
################################################################################

# ---- Hiero

settings.tk-multi-snapshot.hiero:
  template_snapshot: hiero_project_snapshot
  template_work: hiero_project_work
  location: "@apps.tk-multi-snapshot.location"

################################################################################

# ---- Houdini

# asset step
settings.tk-multi-snapshot.houdini.asset_step:
  template_snapshot: houdini_asset_snapshot
  template_work: houdini_asset_work
  location: "@apps.tk-multi-snapshot.location"

# shot step
settings.tk-multi-snapshot.houdini.shot_step:
  template_snapshot: houdini_shot_snapshot
  template_work: houdini_shot_work
  location: "@apps.tk-multi-snapshot.location"

################################################################################

# ---- Maya

# asset step - Model
settings.tk-multi-snapshot.maya.asset_step-model:
  template_snapshot: maya_asset_snapshot_model
  template_work: maya_asset_work
  location: "@apps.tk-multi-snapshot.location"

# asset step - Material
settings.tk-multi-snapshot.maya.asset_step-material:
  template_snapshot: maya_asset_snapshot_material
  template_work: maya_asset_work
  location: "@apps.tk-multi-snapshot.location"

# shot step
settings.tk-multi-snapshot.maya.shot_step:
  template_snapshot: maya_shot_snapshot
  template_work: maya_shot_work
  location: "@apps.tk-multi-snapshot.location"

################################################################################

# ---- Nuke

# asset step
settings.tk-multi-snapshot.nuke.asset_step:
  template_snapshot: nuke_asset_snapshot
  template_work: nuke_asset_work
  location: "@apps.tk-multi-snapshot.location"

# shot step
settings.tk-multi-snapshot.nuke.shot_step:
  template_snapshot: nuke_shot_snapshot
  template_work: nuke_shot_work
  location: "@apps.tk-multi-snapshot.location"

################################################################################

# ---- Photoshop

# asset step
settings.tk-multi-snapshot.photoshop.asset_step:
  template_snapshot: photoshop_asset_snapshot
  template_work: photoshop_asset_work
  location: "@apps.tk-multi-snapshot.location"

# shot step
settings.tk-multi-snapshot.photoshop.shot_step:
  template_snapshot: photoshop_shot_snapshot
  template_work: photoshop_shot_work
  location: "@apps.tk-multi-snapshot.location"

  # shot_step_post
settings.tk-multi-snapshot.photoshop.shot_step_post:
  template_snapshot: photoshop_shot_snapshot
  template_work: photoshop_shot_work
  location: "@apps.tk-multi-snapshot.location"

  # shot_step_render
settings.tk-multi-snapshot.photoshop.shot_step_render:
  template_snapshot: photoshop_shot_snapshot
  template_work: photoshop_shot_work
  location: "@apps.tk-multi-snapshot.location"

  # showroom_step_ar
settings.tk-multi-snapshot.photoshop.showroom_step_ar:
  template_snapshot: photoshop_shot_snapshot
  template_work: photoshop_shot_work
  location: "@apps.tk-multi-snapshot.location"

  # showroom_step_post
settings.tk-multi-snapshot.photoshop.showroom_step_post:
  template_snapshot: photoshop_shot_snapshot
  template_work: photoshop_shot_work
  location: "@apps.tk-multi-snapshot.location"

  # showroom_step_render
settings.tk-multi-snapshot.photoshop.showroom_step_render:
  template_snapshot: photoshop_shot_snapshot
  template_work: photoshop_shot_work
  location: "@apps.tk-multi-snapshot.location"

  # showroom_step_sprite
settings.tk-multi-snapshot.photoshop.showroom_step_sprite:
  template_snapshot: photoshop_shot_snapshot
  template_work: photoshop_shot_work
  location: "@apps.tk-multi-snapshot.location"

################################################################################

# ---- After Effects

# asset step
settings.tk-multi-snapshot.aftereffects.asset_step:
  template_snapshot: aftereffects_asset_snapshot
  template_work: aftereffects_asset_work
  hook_scene_operation: "{engine}/tk-multi-snapshot/basic/scene_operation.py"
  location: "@apps.tk-multi-snapshot.location"

# shot step
settings.tk-multi-snapshot.aftereffects.shot_step:
  template_snapshot: aftereffects_shot_snapshot
  template_work: aftereffects_shot_work
  hook_scene_operation: "{engine}/tk-multi-snapshot/basic/scene_operation.py"
  location: "@apps.tk-multi-snapshot.location"

# shot_step_post
settings.tk-multi-snapshot.aftereffects.shot_step_post:
  template_snapshot: aftereffects_shot_snapshot
  template_work: aftereffects_shot_work
  hook_scene_operation: "{engine}/tk-multi-snapshot/basic/scene_operation.py"
  location: "@apps.tk-multi-snapshot.location"

  # shot_step_render
settings.tk-multi-snapshot.aftereffects.shot_step_render:
  template_snapshot: aftereffects_shot_snapshot
  template_work: aftereffects_shot_work
  hook_scene_operation: "{engine}/tk-multi-snapshot/basic/scene_operation.py"
  location: "@apps.tk-multi-snapshot.location"

  # showroom_step_ar
settings.tk-multi-snapshot.aftereffects.showroom_step_ar:
  template_snapshot: aftereffects_shot_snapshot
  template_work: aftereffects_shot_work
  hook_scene_operation: "{engine}/tk-multi-snapshot/basic/scene_operation.py"
  location: "@apps.tk-multi-snapshot.location"

  # showroom_step_post
settings.tk-multi-snapshot.aftereffects.showroom_step_post:
  template_snapshot: aftereffects_shot_snapshot
  template_work: aftereffects_shot_work
  hook_scene_operation: "{engine}/tk-multi-snapshot/basic/scene_operation.py"
  location: "@apps.tk-multi-snapshot.location"

  # showroom_step_render
settings.tk-multi-snapshot.aftereffects.showroom_step_render:
  template_snapshot: aftereffects_shot_snapshot
  template_work: aftereffects_shot_work
  hook_scene_operation: "{engine}/tk-multi-snapshot/basic/scene_operation.py"
  location: "@apps.tk-multi-snapshot.location"
  
  # showroom_step_sprite
settings.tk-multi-snapshot.aftereffects.showroom_step_sprite:
  template_snapshot: aftereffects_shot_snapshot
  template_work: aftereffects_shot_work
  hook_scene_operation: "{engine}/tk-multi-snapshot/basic/scene_operation.py"
  location: "@apps.tk-multi-snapshot.location"


################################################################################

# ---- Motion Builder

# asset step
settings.tk-multi-snapshot.motionbuilder.asset_step:
  template_snapshot: mobu_asset_snapshot
  template_work: mobu_asset_work
  location: "@apps.tk-multi-snapshot.location"

# shot step
settings.tk-multi-snapshot.motionbuilder.shot_step:
  template_snapshot: mobu_shot_snapshot
  template_work: mobu_shot_work
  location: "@apps.tk-multi-snapshot.location"
