# SG Pipeline Toolkit configuration file
# This file was automatically created by setup_project
# This file reflects the paths in the primary pipeline
# configuration defined for this project.

Windows: 'B:\Shotgrid\configs\sandbox'
Darwin: '/Volumes/SOFTWARE/Shotgrid/configs/sandbox'
Linux: ''

# End of file.
